# Site settings
site: Tolga Koyuncu
title: Tolga Koyuncu
keywords: Tolga Koyuncu, blog, yazılım geliştirme, siber güvenlik, programlama, c programlama dili
description: >-
  Tolga Koyuncu Kişisel Blog Sitesi. Bilgisayar mühendisliği, yazılım geliştirme, siber güvenlik ve çeşitli konularda blog gönderilerine erişebilirsiniz.
lang: tr-TR
timezone:  Europe/Istanbul
repo: https://github.com/koyuncutlg # site repo [optional]


# Author settings
author:
  name: Tolga Koyuncu
  bio: Computer Engineer @XON <br> AI & ML & LLM <br> Open Source /#linux
  picture: assets/images/tolga-koyuncu.jpg
  github: koyuncutlg # github username
  twitter: koyuncutlg # twitter username
  facebook: koyuncutlg # facebook username
  instagram: koyuncutlg # instagram username
  youtube: koyuncutlg # youtube username
  email: tolga_koyuncu[hirobot]hotmail.com # email adress


# URL settings
url: "https://koyuncutlg.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false